wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1675569220.847015
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 17
      - 23
      - 37
      4: 3.7.11
      5: 0.13.1
      8:
      - 1
      - 5
      10:
      - 3
